name: Integration tests
on:
  push:
    paths:
      - 'src/**'

jobs:
  run-integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Write key and certificate to files
        run: |
          echo "${{ secrets.AZUL_KEY }}" > ./key.pem
          echo "${{ secrets.AZUL_CERT }}" > ./cert.pem
      - run: npm ci
      - run: npm run test